### ISSUE TITLE
[DOCS] how_to/distribute_anntoation_work

### ISSUE THREAD

**Issue by sdiazlor** [argilla-io/argilla-python#186]
Learn how to distribute Records to Users and Workspaces for managing annotation efforts the way you require.

**Comment by nataliaElv** [comment]
@sdiazlor We are expecting to  release a feature to automatically distribute records in `2.1.0`. Maybe it makes sense to close this issue or at least put it on hold until this feature is out. Otherwise you might end up doing a lot of work that will get substituted soon. Let me know what you want to do and whether you want me to move this issue to the `argilla` repo or not.

**Comment by sdiazlor** [comment]
@nataliaElv I agree on that, I knew you were working on this, so I didn't worry too much. It was just to keep it in mind. You can close it and we'll iterate on the docs when added.
